name: sync

on:
  workflow_dispatch: {}

jobs:
  docker_to_alihz:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - src: "elasticsearch:8.11.3"
            dst: "acr-maas-bj-registry.cn-beijing.cr.aliyuncs.com/maas/elasticsearch:8.11.3"
          - src: "mysql:8.0.39"
            dst: "acr-maas-bj-registry.cn-beijing.cr.aliyuncs.com/maas/mysql:8.0.39"
          - src: "quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z"
            dst: "acr-maas-bj-registry.cn-beijing.cr.aliyuncs.com/maas/minio:RELEASE.2025-06-13T11-33-47Z"
          - src: "valkey/valkey:8"
            dst: "acr-maas-bj-registry.cn-beijing.cr.aliyuncs.com/maas/valkey:8"
          - src: "kibana:8.11.3"
            dst: "acr-maas-bj-registry.cn-beijing.cr.aliyuncs.com/maas/kibana:8.11.3"
    steps:
      - name: Sync Docker Images
        run: |
          #!/usr/bin/env bash

          set -euxo pipefail

          sync_image() {
              local src_img=$1
              local dst_img=$2

              echo "Copying from source to destination..."
              skopeo copy docker://"${src_img}" docker://"${dst_img}" \
                  --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
          }

          sync_image "${{ matrix.src }}" "${{ matrix.dst }}"
