name: sync

on:
  workflow_dispatch: {}

jobs:
  docker_to_alihz:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - src: "registry.k8s.io/scheduler-plugins/controller:v0.27.8"
            dst: "acr-maas-bj-registry.cn-beijing.cr.aliyuncs.com/maas/scheduler-plugins/controller:v0.27.8"
          - src: "registry.k8s.io/scheduler-plugins/kube-scheduler:v0.27.8"
            dst: "acr-maas-bj-registry.cn-beijing.cr.aliyuncs.com/maas/scheduler-plugins/kube-scheduler:v0.27.8"
          - src: "registry.k8s.io/jobset/jobset:v0.2.0"
            dst: "acr-maas-bj-registry.cn-beijing.cr.aliyuncs.com/maas/jobset/jobset:v0.2.0"
    steps:
      - name: Sync Docker Images
        run: |
          #!/usr/bin/env bash

          set -euxo pipefail

          sync_image() {
              local src_img=$1
              local dst_img=$2

              echo "Copying from source to destination..."
              skopeo copy --all docker://"${src_img}" docker://"${dst_img}" \
                  --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
          }

          sync_image "${{ matrix.src }}" "${{ matrix.dst }}"
