name: sync

on:
  workflow_dispatch: {}

jobs:
  docker_to_alihz:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - src: "quay.io/repository/ascend/verl:verl-8.5.0-910b-ubuntu22.04-py3.11-v0.7.1"
            dst: "acr-maas-bj-registry.cn-beijing.cr.aliyuncs.com/maas/verl:verl-8.5.0-910b-ubuntu22.04-py3.11-v0.7.1"
    steps:
      - name: Sync Docker Images
        run: |
          #!/usr/bin/env bash

          set -euxo pipefail

          sync_image() {
              local src_img=$1
              local dst_img=$2

              echo "Copying from source to destination..."
              skopeo copy docker://"${src_img}" docker://"${dst_img}" \
                  --dest-creds=${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}
          }

          sync_image "${{ matrix.src }}" "${{ matrix.dst }}"
